- name: configuring cart
  hosts: cart
  become: yes
  tasks:
  - name: disable default nodejs module
    ansible.builtin.command: dnf module disable nodejs -y
  - name: enable the nodejs:20 
    ansible.builtin.command: dnf module enable nodejs:20 -y
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  - name: creating app directory
    ansible.builtin.file:
     path: /app 
     state: directory
  - name: creating a system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app


  - name: downloading the cart file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip
  - name: unzipping the cart code
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app 
      remote_src: yes
  - name: installing dependencies
    community.general.npm:
      path: /app
  - name: copying the cart service file
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service
  - name: daemon-reload the service
    ansible.builtin.systemd_service:
      daemon_reload: true
  - name: enable the cart
    ansible.builtin.service:
      name: cart
      state: started
      enabled: yes

  
