- name: configuring catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disable default nodejs module
    ansible.builtin.command: dnf module disable nodejs -y
  - name: enable the nodejs:20 
    ansible.builtin.command: dnf module enable nodejs:20 -y
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  - name: creating a system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      

      