- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    instances:
    - mysql
    - frontend
    - backend
  subnet_id: subnet-03baa930fd25ac0a1
  sg_id: sg-0ed01617e03501426

  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"  
      image_id: ami-09c813fb71547fc4f
      tags:
        name: "{{ item }}"
    loop: "{{ instances }}" 

