- name: configuring rabbitmq server
  hosts: rabbitmq
  become: yes
  tasks:
  - name: copying the rabbitmq repo
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo
  - name: installing rabbitmq
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: present
  - name: start and enable rabbitmq
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes
  - name: adding the user
    community.mysql.mysql_info:
      login_user: shipping
      login_password: RoboShop@1
      login_host: mysql.prasannadevops.online
      login_db: cities
      
